name = "standalone"
[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
enable_cgo = true
skip_runtime_image = true

[runners."local:docker"]
enabled = true

[[testcases]]
name= "standalone"
instances = { min = 1, max = 5, default = 1 }
