name = "standalone"
[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
enable_cgo = true
skip_runtime_image = true

[runners."local:docker"]
enabled = true

[[testcases]]
name= "DMapGetPut"
instances = { min = 1, max = 1, default = 1 }

[[testcases]]
name= "DMapPutDelete"
instances = { min = 1, max = 1, default = 1 }

[[testcases]]
name= "DMapPutEx"
instances = { min = 1, max = 1, default = 1 }

[[testcases]]
name= "DMapPutIf"
instances = { min = 1, max = 1, default = 1 }